baseurl = "https://www.techu5iad.best/"
languageCode = "en-us"
title = "Tech U Cohort 5"
theme = "my-hugo-cards"
#themesDir = "../.."
paginate = 6

[params]
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/bul_ikana"
  github = "http://github.com/bul-ikana"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""
